version: '3'
volumes:
  logs:
    driver: local
  db:
    driver: local
  matomo:
    driver: local
services:
  # MySQL database
  database:
    image: mariadb
    restart: always
    env_file:
      - .env.dist
    environment: 
      - MYSQL_ROOT_PASSWORD
    ports:
      - 3306
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql

  # Php 8 + apache
  server:
    build:
      context: ./server/
    links:
      - database:database
    working_dir: /var/www/html
    ports:
      - 8888:80
    env_file:
      - .env.dist
      - .env

  # Angular client running on nginx
  client:
    build:
      context: ./client/
      args:
        NG_ENV: local
    restart: always
    ports:
      - 4000:80

  # db admin
  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080
    env_file:
      - .env.dist
      - .env
    links:
      - database:database

  tracker:
    image: matomo
    restart: always
    volumes:
#     - ./config:/var/www/html/config
#     - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=database
      - VIRTUAL_HOST=tracker.resum
    env_file:
      - .env.dist
      - .env
    ports:
      - 7000:80

  tests:
    build:
      context: ./tests/
      args:
        RESUM_HOST: http://localhost:80/
    restart: always
    ports:
      - 8000:8080

