allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  nice-napi: true
  nx: true
minimumReleaseAgeExclude:
  - "@angular-devkit/architect@0.2102.16"
  - "@angular-devkit/core@21.2.16"
  - "@angular-devkit/schematics@21.2.16"
  - "@angular/build@21.2.16"
  - "@angular/cli@21.2.16"
  - "@angular/ssr@21.2.16"
  - "@schematics/angular@21.2.16"
  - '@angular-devkit/architect@0.2200.2'
  - '@angular-devkit/core@22.0.2'
  - '@angular-devkit/schematics@22.0.2'
  - '@angular/cli@22.0.2'
  - '@schematics/angular@22.0.2'
