name: Deploy to prod

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  NITRO_PRESET: 'cloudflare'
  NODE_VERSION: '24.x'
  PNPM_VERSION: '11'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Build (angular)
        run: pnpm run build

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: pnpm

      - name: print deployment-url
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL
