name: Deploy to prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Build (angular)
        run: pnpm run build

      - name: Deploy
        uses: sand4rt/ftp-deployer@v1.7
        with:
          sftp: true
          host: ${{ secrets.FTP_HOST }}
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remote_folder: ${{ secrets.FTP_REMOTE_FOLDER }}
          local_folder: 'dist/analog/public'
          cleanup: true
          include: '["*", "**/*", ".*"]'
